name: djangrib

channels:
  - conda-forge

dependencies:
  - django
  - gunicorn
  - netCDF4
  - pygrib
  - pip
  - pip:
    - psycopg2
    - django-widget-tweaks
    - first
    - selenium
    - python-dotenv
